# Use a imagem base do Node.js
FROM node:22-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o package.json e o package-lock.json para o contêiner
COPY package*.json ./

# Instala as dependências do projeto
# Isso é feito separadamente para aproveitar o cache do Docker
RUN npm install

# Copia o restante do código da aplicação
COPY . .

# Expõe a porta que o Vite usa para o servidor de desenvolvimento
EXPOSE 5173

# O comando para iniciar o servidor de desenvolvimento com hot-reload
# O '--host' permite que o servidor seja acessado de fora do contêiner
CMD ["npm", "run", "dev", "--", "--host"]