services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # Mapeia o código-fonte local, mas isola a node_modules
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
